# Generated by Django 5.2.3 on 2025-06-19 01:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FlowFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='File Name')),
                ('header', models.CharField(blank=True, max_length=255, null=True, verbose_name='Header')),
                ('footer', models.CharField(blank=True, max_length=255, null=True, verbose_name='Footer')),
                ('uploaded_at', models.DateTimeField(blank=True, default=None, null=True)),
            ],
            options={
                'verbose_name': 'Flow File',
                'verbose_name_plural': 'Flow Files',
                'ordering': ('-id',),
            },
        ),
        migrations.CreateModel(
            name='MeterReading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mpan_core', models.CharField(blank=True, max_length=255, null=True, verbose_name='MPAN Core')),
                ('bsc_validation_status', models.CharField(blank=True, max_length=255, null=True, verbose_name='BSC Validation Status')),
                ('site_visit_check_code', models.CharField(blank=True, max_length=255, null=True, verbose_name='Site Visit Check Code')),
                ('additional_information', models.TextField(blank=True, null=True, verbose_name='Additional Information')),
                ('meter_id', models.CharField(blank=True, max_length=255, null=True, verbose_name='Meter Id (Serial Number)')),
                ('reading_type', models.CharField(blank=True, max_length=255, null=True, verbose_name='Reading Type')),
                ('meter_register_id', models.CharField(blank=True, max_length=255, null=True, verbose_name='Meter Register Id')),
                ('reading_date_time', models.DateTimeField(blank=True, null=True, verbose_name='Reading Date & Time')),
                ('register_reading', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Register Reading')),
                ('md_reset_date_time', models.DateTimeField(blank=True, null=True, verbose_name='MD Reset Date & Time')),
                ('number_of_md_resets', models.IntegerField(blank=True, null=True, verbose_name='Number of MD Resets')),
                ('meter_reading_flag', models.BooleanField(default=None, null=True, verbose_name='Meter Reading Flag')),
                ('reading_method', models.CharField(blank=True, max_length=255, null=True, verbose_name='Reading Method')),
                ('meter_reading_reason_code', models.CharField(blank=True, max_length=255, null=True, verbose_name='Meter Reading Reason Code')),
                ('meter_reading_status', models.CharField(blank=True, max_length=255, null=True, verbose_name='Meter Reading Status')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('file_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='readings.flowfile')),
            ],
            options={
                'verbose_name': 'Meter Reading',
                'ordering': ('-id',),
            },
        ),
    ]
